# Generated by Django 4.2.16 on 2026-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_event_rsvp_questions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collect_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_qr',
            field=models.ImageField(blank=True, upload_to='portal/payment_qr/'),
        ),
        migrations.AddField(
            model_name='event',
            name='require_profile_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='payment_screenshot',
            field=models.ImageField(blank=True, upload_to='portal/payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='rsvp_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='rsvp_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='eventannouncement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='rsvp_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
