# Generated by Django 4.2.16 on 2026-08-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_event_payment_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
