# Generated by Django 4.2.16 on 2026-08-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_flickcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flick',
            name='source_video_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
