# Generated by Django 4.2.16 on 2026-08-21 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0010_flick_source_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flick',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_flicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('event_coordinator', 'Event Coordinator'), ('volunteer_coordinator', 'Volunteer Coordinator'), ('media_coordinator', 'Media Coordinator'), ('member', 'Member')], max_length=30),
        ),
    ]
