# Generated by Django 4.2.16 on 2026-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='join_mode',
            field=models.CharField(choices=[('open', 'Open Join'), ('approval', 'Admin Approval'), ('private', 'Private — Invite Only')], default='open', max_length=10),
        ),
    ]
