# Generated by Django 4.2.16 on 2026-09-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_community_join_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
