# Generated by Django 4.2.16 on 2026-09-10 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0015_community_points_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.CharField(choices=[('organiser', 'Organiser'), ('volunteer', 'Volunteer'), ('contributor', 'Contributor'), ('guest', 'Guest'), ('sponsor', 'Sponsor'), ('performer', 'Performer'), ('leadership', 'Leadership'), ('bonus', 'Bonus Points')], default='attendee', max_length=15),
        ),
        migrations.CreateModel(
            name='AttendeeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_ratings', to='portal.event')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_attendee_ratings', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_attendee_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'rater', 'ratee')},
            },
        ),
    ]
