# Generated by Django 4.2.16 on 2026-06-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_wallet_wallettransaction_usernotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='availability',
            field=models.CharField(choices=[('immediate', 'Immediate Joiner'), ('within_1month', 'Within 1 Month'), ('within_3months', 'Within 3 Months'), ('not_looking', 'Not Actively Looking')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers', to='jobs.district'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=15),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='open_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seeker_photos/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='portfolio_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_pincode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_roles',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='salary_type',
            field=models.CharField(choices=[('month', 'Per Month'), ('day', 'Per Day'), ('hour', 'Per Hour')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers', to='jobs.state'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='job_category',
            field=models.CharField(choices=[('white', 'White Collar'), ('blue', 'Blue Collar'), ('any', 'Any')], default='any', max_length=10),
        ),
        migrations.CreateModel(
            name='SeekerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('issued_year', models.CharField(blank=True, max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='jobs.jobseekerprofile')),
            ],
        ),
    ]
