# Generated by Django 4.2.16 on 2026-06-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_message_file_message_file_name_message_invite_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('shop', 'Shop'), ('factory', 'Factory'), ('startup', 'Startup'), ('institution', 'Institution'), ('ngo', 'NGO'), ('hospital', 'Hospital'), ('hotel', 'Hotel / Restaurant'), ('farm', 'Farm'), ('individual_employer', 'Individual Employer'), ('employee', 'Employee'), ('individual', 'Individual'), ('freelancer', 'Freelancer'), ('advertiser', 'Advertiser')], default='employee', max_length=20),
        ),
    ]
