# Generated by Django 4.2.16 on 2026-06-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_advertiser_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='logo',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertiser_banners/'),
        ),
    ]
