# Generated by Django 4.2.16 on 2026-06-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_advertiser_logo_advertiser_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
