# Generated by Django 4.2.16 on 2026-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_delete_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('shop', 'Shop'), ('recruiter', 'Recruiter / Placement Agency'), ('factory', 'Factory'), ('startup', 'Startup'), ('institution', 'Institution'), ('ngo', 'NGO'), ('hospital', 'Hospital'), ('hotel', 'Hotel / Restaurant'), ('farm', 'Farm'), ('individual_employer', 'Individual Employer'), ('employee', 'Employee'), ('individual', 'Individual'), ('freelancer', 'Freelancer'), ('advertiser', 'Advertiser')], default='employee', max_length=20),
        ),
    ]
