# Generated by Django 4.2.16 on 2026-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_industry_max_length_300'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
