# Generated by Django 4.2.16 on 2026-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_add_unique_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='description',
            field=models.TextField(blank=True, help_text='About your business / what you offer'),
        ),
    ]
