# Generated by Django 4.2.16 on 2026-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_referral_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('walkin', 'Walk-in Drive'), ('online', 'Online Interview')], default='walkin', max_length=10),
        ),
    ]
