# Generated by Django 4.2.16 on 2026-07-15 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_add_interview_type_to_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('caption', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='flicks/videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flicks/images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlickComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.flick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flick_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlickLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='jobs.flick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flick_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flick', 'user')},
            },
        ),
    ]
