# Generated by Django 4.2.16 on 2026-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_add_flick_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='flick',
            name='advertise_plan',
            field=models.CharField(blank=True, choices=[('', 'No Plan'), ('basic', 'Basic'), ('premium', 'Premium'), ('featured', 'Featured')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='flick',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
