# Generated by Django 4.2.16 on 2026-07-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_add_flick_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ad_posts/')),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reject_note', models.TextField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('renewal_price', models.PositiveIntegerField(default=199)),
                ('renewal_days', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Ad Settings',
            },
        ),
        migrations.CreateModel(
            name='FlickAdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='mypincod@upi', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=499, max_digits=10)),
                ('duration_days', models.IntegerField(default=84)),
            ],
            options={
                'verbose_name': 'Flick Ad Settings',
            },
        ),
        migrations.AddField(
            model_name='flick',
            name='advertise_plan',
            field=models.CharField(blank=True, choices=[('', 'No Plan'), ('basic', 'Basic'), ('premium', 'Premium'), ('featured', 'Featured')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='flick',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flick',
            name='promoted_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlickAdPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=84)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_payments', to='jobs.flick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flick_ad_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200)),
                ('screenshot', models.ImageField(upload_to='ad_renewals/')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reject_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='jobs.adpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlickReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam or Misleading'), ('violence', 'Violence or Dangerous'), ('harassment', 'Harassment or Bullying'), ('misinformation', 'False Information'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.flick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flick_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('flick', 'user')},
            },
        ),
    ]
