# Generated by Django 4.2.16 on 2026-07-17 10:21
# Operations emptied: all schema changes are applied by the 0025_flick→0030 chain.
# This migration is kept for dependency resolution by 0031_merge.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_add_flick_models'),
    ]

    operations = []
