# Generated by Django 4.2.16 on 2026-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_adpost_adsettings_flickadsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flick',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('health', 'Health'), ('job', 'Job'), ('business', 'Business')], default='general', max_length=20),
        ),
    ]
