# Generated by Django 4.2.16 on 2026-07-16 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_flick_advertise_plan_flick_is_promoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickAdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='mypincod@upi', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=499, max_digits=10)),
                ('duration_days', models.IntegerField(default=84)),
            ],
            options={
                'verbose_name': 'Flick Ad Settings',
            },
        ),
        migrations.AddField(
            model_name='flick',
            name='promoted_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlickAdPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=84)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_payments', to='jobs.flick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flick_ad_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
