# Generated by Django 4.2.16 on 2026-07-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_adpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('renewal_price', models.PositiveIntegerField(default=199)),
            ],
            options={
                'verbose_name': 'Ad Settings',
            },
        ),
        migrations.AddField(
            model_name='adpost',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200)),
                ('screenshot', models.ImageField(upload_to='ad_renewals/')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reject_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='jobs.adpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
