# Generated by Django 4.2.16 on 2026-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_adsettings_adpost_expires_at_adrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsettings',
            name='renewal_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
