# Generated by Django 4.2.16 on 2026-07-17 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_adsettings_renewal_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam or Misleading'), ('violence', 'Violence or Dangerous'), ('harassment', 'Harassment or Bullying'), ('misinformation', 'False Information'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.flick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flick_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('flick', 'user')},
            },
        ),
    ]
