# Generated by Django 4.2.16 on 2026-07-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_adpost_adsettings_flickadsettings_and_more'),
        ('jobs', '0030_flickreport'),
    ]

    operations = [
    ]
