# Generated by Django 4.2.16 on 2026-08-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_spin_to_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('shop', 'Shop'), ('recruiter', 'Recruiter / Placement Agency'), ('factory', 'Factory'), ('startup', 'Startup'), ('institution', 'Institution'), ('ngo', 'NGO'), ('hospital', 'Hospital'), ('hotel', 'Hotel / Restaurant'), ('farm', 'Farm'), ('individual_employer', 'Individual Employer'), ('employee', 'Employee'), ('individual', 'Individual'), ('freelancer', 'Freelancer'), ('advertiser', 'Advertiser'), ('family_child', 'Family Child Account')], default='employee', max_length=20),
        ),
    ]
