# Generated by Django 4.2.16 on 2026-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_alter_user_user_type'),
        ('jobs', '0034_localoffer'),
    ]

    operations = [
    ]
