# Generated by Django 4.2.16 on 2026-08-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_merge_0034_alter_user_user_type_0034_localoffer'),
        ('jobs', '0037_localoffer_valid_days'),
    ]

    operations = [
    ]
