# Generated by Django 4.2.16 on 2026-08-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_merge_20260828_1333'),
        ('jobs', '0039_localoffer_category_maxlength'),
    ]

    operations = [
    ]
