# Generated by Django 4.2.16 on 2026-08-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_merge_20260828_1408'),
        ('jobs', '0040_user_business_phone'),
    ]

    operations = [
    ]
