# Generated by Django 4.2.16 on 2026-08-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_merge_20260828_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localoffer',
            name='valid_days',
            field=models.CharField(blank=True, help_text='Comma-separated days e.g. Mon,Tue for recurring weekly offers', max_length=50),
        ),
    ]
