# Generated by Django 4.2.16 on 2026-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_jobapplication_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20),
        ),
    ]
