# Generated by Django 4.2.16 on 2026-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_alter_adpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_banners/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_banners/'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
