# Generated by Django 4.2.16 on 2026-09-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_alter_adpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_covers/'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='shop_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.shopprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
