# Generated by Django 4.2.16 on 2026-09-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_add_business_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='blue_collar_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
