# Generated by Django 4.2.16 on 2026-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_jobseekerprofile_blue_collar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salesman_biz_id',
            field=models.CharField(blank=True, help_text='Unique ID shared with salesman for business linkage', max_length=16, null=True, unique=True),
        ),
    ]
