# Generated by Django 4.2.16 on 2026-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponbatch',
            name='distributed_date',
            field=models.DateField(blank=True, help_text='Date coupons were physically distributed', null=True),
        ),
    ]
