# Generated by Django 4.2.16 on 2026-08-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_school_corner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('academics', 'Academics'), ('sports', 'Sports'), ('arts', 'Arts & Culture'), ('music', 'Music'), ('scholarship', 'Scholarship'), ('competition', 'Competition'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_success/')),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_successes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Successes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSuccessComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.studentsuccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSuccessLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.studentsuccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'success')},
            },
        ),
    ]
