# Generated by Django 4.2.16 on 2026-08-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0015_school_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('pet', 'Pet / Animal'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('why', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_members/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('about', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('house_name', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('living', 'Living'), ('passed', 'Passed Away')], default='living', max_length=10)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
