# Generated by Django 4.2.16 on 2026-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='vice_principal',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
