# Generated by Django 4.2.16 on 2026-08-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0017_school_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandfather_count', models.PositiveSmallIntegerField(default=0)),
                ('grandmother_count', models.PositiveSmallIntegerField(default=0)),
                ('father_count', models.PositiveSmallIntegerField(default=0)),
                ('mother_count', models.PositiveSmallIntegerField(default=0)),
                ('son_count', models.PositiveSmallIntegerField(default=0)),
                ('daughter_count', models.PositiveSmallIntegerField(default=0)),
                ('uncle_count', models.PositiveSmallIntegerField(default=0)),
                ('aunt_count', models.PositiveSmallIntegerField(default=0)),
                ('cousin_count', models.PositiveSmallIntegerField(default=0)),
                ('pet_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_setup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
