# Generated by Django 4.2.16 on 2026-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_family_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('teacher', 'Teacher')], default='admin', max_length=10),
        ),
    ]
