# Generated by Django 4.2.16 on 2026-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_school_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
