# Generated by Django 4.2.16 on 2026-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_school_admin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysetup',
            name='brother_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='sister_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(choices=[('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('brother', 'Brother'), ('sister', 'Sister'), ('pet', 'Pet / Animal'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolpost',
            name='post_type',
            field=models.CharField(choices=[('annual_day', '🎭 Annual Day'), ('sports_day', '⚽ Sports Day'), ('science_fair', '🔬 Science Fair'), ('achievement', '🏆 Achievement'), ('event', '📅 Event'), ('announcement', '📢 Announcement'), ('other', '📌 Other')], default='other', max_length=20),
        ),
    ]
