# Generated by Django 4.2.16 on 2026-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_familysetup_brother_count_familysetup_sister_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysetup',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=12),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='setup_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='familysetup',
            name='village',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
