# Generated by Django 4.2.16 on 2026-08-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_familysetup_age_familysetup_display_name_and_more'),
        ('community', '0023_family_wife_side'),
    ]

    operations = [
    ]
