# Generated by Django 4.2.16 on 2026-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_familysetup_partner_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpost',
            name='post_type',
            field=models.CharField(choices=[('daily', '📌 Daily'), ('annual_day', '🎭 Annual Day'), ('sports_day', '⚽ Sports Day'), ('science_fair', '🔬 Fair'), ('achievement', '🏆 Achievement'), ('event', '📅 Event'), ('announcement', '📢 Announcement'), ('other', '📌 Other')], default='other', max_length=20),
        ),
    ]
