# Generated by Django 4.2.16 on 2026-08-29 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0028_alter_schoolpost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(choices=[('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('pet', 'Pet / Animal'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='FamilyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_post_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyFlick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='family_flicks/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_flicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
