# Generated by Django 4.2.16 on 2026-09-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_familyflick_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
