# Generated by Django 4.2.16 on 2026-09-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_merge_20260821_1145'),
        ('community', '0029_event_deleted_at'),
        ('community', '0029_flick_post'),
    ]

    operations = [
    ]
