# Generated by Django 4.2.16 on 2026-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_merge_20260902_2047'),
        ('community', '0028_familyflick_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(choices=[('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('pet', 'Pet / Animal'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolpost',
            name='post_type',
            field=models.CharField(choices=[('daily', '📌 Daily'), ('annual_day', '🎭 Annual Day'), ('sports_day', '⚽ Sports Day'), ('science_fair', '🔬 Fair'), ('achievement', '🏆 Achievement'), ('event', '📅 Event'), ('announcement', '📢 Announcement'), ('other', '📌 Other')], default='other', max_length=20),
        ),
    ]
