# Generated by Django 4.2.16 on 2026-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_familyflick_video_alter_familyflick_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyflick',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
