# Generated by Django 4.2.16 on 2026-09-04 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0032_gallery_timeline_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob_owner_key', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('notif_type', models.CharField(choices=[('reminder', 'Reminder'), ('today', 'Today')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_notif_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dob_owner_key', 'year', 'notif_type')},
            },
        ),
    ]
