# Generated by Django 4.2.16 on 2026-08-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='target_institutions',
            field=models.ManyToManyField(blank=True, related_name='targeted_opportunities', to='campus.institution'),
        ),
    ]
