# Generated by Django 4.2.16 on 2026-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_add_target_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementofficer',
            name='phone2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
