# Generated by Django 4.2.16 on 2026-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_add_phone2_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
