# Generated by Django 4.2.16 on 2026-07-24 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vouchers/business/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='vouchers/business/covers/')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('payment_gateway_key', models.CharField(blank=True, max_length=200)),
                ('payment_gateway_secret', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Business Category',
                'verbose_name_plural': 'Business Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=200)),
                ('product_service_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='vouchers/products/')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='vouchers/headers/')),
                ('voucher_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('valid_from', models.DateField()),
                ('expiry_date', models.DateField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_branches', models.ManyToManyField(blank=True, related_name='vouchers', to='vouchers.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_vouchers', to='vouchers.business')),
            ],
            options={
                'verbose_name': 'Gift Voucher',
                'verbose_name_plural': 'Gift Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Voucher Category',
                'verbose_name_plural': 'Voucher Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoucherPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=30, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vouchers/qrcodes/')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_mobile', models.CharField(max_length=15)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_mobile', models.CharField(max_length=15)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('personal_message', models.TextField(blank=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('sent', 'Sent to Receiver'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_vouchers', to=settings.AUTH_USER_MODEL)),
                ('gift_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vouchers.giftvoucher')),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Purchase',
                'verbose_name_plural': 'Voucher Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSlotPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_count', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_purchases', to='vouchers.business')),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Slot Purchase',
                'verbose_name_plural': 'Voucher Slot Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='vouchers.branch')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='vouchers.voucherpurchase')),
                ('redeemed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Redemption',
                'verbose_name_plural': 'Voucher Redemptions',
            },
        ),
        migrations.CreateModel(
            name='VoucherAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Voucher Created'), ('published', 'Voucher Published'), ('paused', 'Voucher Paused'), ('purchased', 'Voucher Purchased'), ('sent', 'Voucher Sent'), ('otp_generated', 'OTP Generated'), ('otp_failed', 'OTP Failed'), ('redeemed', 'Voucher Redeemed'), ('expired', 'Voucher Expired'), ('cancelled', 'Voucher Cancelled')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vouchers.giftvoucher')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vouchers.voucherpurchase')),
            ],
            options={
                'verbose_name': 'Voucher Audit Log',
                'verbose_name_plural': 'Voucher Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.vouchercategory'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('business_owner', 'Business Owner'), ('marketing_manager', 'Marketing Manager'), ('branch_manager', 'Branch Manager')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='vouchers.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='vouchers.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.businesscategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='vouchers.business'),
        ),
    ]
