# Generated by Django 4.2.16 on 2026-08-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_jobapplication_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='localoffer',
            name='valid_days',
            field=models.CharField(blank=True, help_text='Comma-separated days e.g. Mon,Tue for recurring weekly offers', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('shop', 'Shop'), ('recruiter', 'Recruiter / Placement Agency'), ('factory', 'Factory'), ('startup', 'Startup'), ('institution', 'Institution'), ('ngo', 'NGO'), ('hospital', 'Hospital'), ('hotel', 'Hotel / Restaurant'), ('farm', 'Farm'), ('individual_employer', 'Individual Employer'), ('employee', 'Employee'), ('individual', 'Individual'), ('freelancer', 'Freelancer'), ('advertiser', 'Advertiser'), ('family_child', 'Family Child Account')], default='employee', max_length=20),
        ),
    ]
