# Generated by Django 4.2.16 on 2026-08-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_alter_localoffer_valid_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
