# Generated by Django 4.2.16 on 2026-08-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_adpost_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='description',
            field=models.CharField(max_length=160),
        ),
    ]
