"""
Django settings for jobportal project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if present (development convenience)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

SITE_NAME    = 'MY PINCOD'
SITE_TAGLINE = 'Find Jobs Near You. Hire People Near You.'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-!22xkr*k3tn!jmif%n$@^1e+jzm5yl1d7!d(80u4*$#h$1-k!')

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# Load from environment — do NOT hardcode here
TWO_FACTOR_API_KEY = os.environ.get('TWO_FACTOR_API_KEY', '')
TWO_FACTOR_OTP_TEMPLATE = 'OTP1'

DEBUG = False

ALLOWED_HOSTS = ['mypincod.com', 'www.mypincod.com']
CSRF_TRUSTED_ORIGINS = ['https://mypincod.com', 'https://www.mypincod.com']

# ── Security headers ─────────────────────────────────────────────────────────
SECURE_SSL_REDIRECT          = True
SECURE_HSTS_SECONDS          = 31536000   # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF  = True
SESSION_COOKIE_SECURE        = True
SESSION_COOKIE_HTTPONLY      = True
CSRF_COOKIE_SECURE           = True
CSRF_COOKIE_HTTPONLY         = False   # must be False — JS needs to read it for AJAX
X_FRAME_OPTIONS              = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jobs',
    'health',
    'vouchers',
    'community',
    'campus',
    'portal',
]

AUTH_USER_MODEL = 'jobs.User'

AUTHENTICATION_BACKENDS = [
    'jobs.backends.PhoneOrEmailBackend',
    'jobs.backends.FamilyAccountBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL          = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'jobportal.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'jobportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'jobs.context_processors.site_ads',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     os.environ.get('DB_NAME', 'localjobs_db'),
        'USER':     os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST':     os.environ.get('DB_HOST', 'localhost'),
        'PORT':     os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_ALL_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Email (Gmail SMTP) ───────────────────────────────────────────────────────
EMAIL_BACKEND      = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST         = 'smtp.gmail.com'
EMAIL_PORT         = 465
EMAIL_USE_TLS      = False
EMAIL_USE_SSL      = True
EMAIL_HOST_USER    = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'OUR PINCODE <{EMAIL_HOST_USER}>')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# ── Cache (file-based, shared across workers) ────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache_mypincod',
        'TIMEOUT': 300,
    }
}

# ── Logging ───────────────────────────────────────────────────────────────────
# Production: Gunicorn captures stderr → systemd journal (service: mypincod).
# Read logs with: sudo journalctl -u mypincod -f
# Development: DEBUG=True causes the console handler to activate automatically.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Application loggers — ERROR+ always; includes full traceback via logger.exception()
        'jobs': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'community': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'portal': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'health': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'campus': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'vouchers': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django framework — request errors and security warnings
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

try:
    from .local_settings import *
except ImportError:
    pass

# ── Sentry error monitoring ───────────────────────────────────────────────────
# Activated only when SENTRY_DSN env var is set (production/staging).
# Never set SENTRY_DSN in development — errors stay local.
_SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if _SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    import logging

    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            # Capture WARNING+ log messages as breadcrumbs; ERROR+ as events
            LoggingIntegration(level=logging.WARNING, event_level=logging.ERROR),
        ],
        # Capture 10 % of transactions for performance data (low overhead)
        traces_sample_rate=0.1,
        # Do not send passwords, tokens, OTPs, or card numbers
        send_default_pii=False,
        environment=os.environ.get('DJANGO_ENV', 'production'),
        release=os.environ.get('GIT_COMMIT', ''),
    )
