# Generated by Django 4.2.16 on 2026-07-17 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_glasses', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_diaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🩺', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/conditions/')),
                ('overview', models.TextField(blank=True)),
                ('foods_to_eat', models.TextField(blank=True)),
                ('foods_to_limit', models.TextField(blank=True)),
                ('fruits_info', models.TextField(blank=True)),
                ('vegetables_info', models.TextField(blank=True)),
                ('herbs_info', models.TextField(blank=True)),
                ('spices_info', models.TextField(blank=True)),
                ('cooking_methods', models.TextField(blank=True)),
                ('meal_timing', models.TextField(blank=True)),
                ('portion_guidance', models.TextField(blank=True)),
                ('faq', models.TextField(blank=True, help_text='JSON: [{"q":"...","a":"..."}]')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=200)),
                ('ai_system_prompt', models.TextField(default="You are a friendly healthy food guide assistant for MY PINCOD. Answer only food and nutrition questions. Give clear, simple answers in easy English. Never diagnose diseases or replace a doctor. Always end every response with: '⚠️ This is educational information only, not medical advice. Please consult your doctor.'")),
                ('daily_tip', models.TextField(blank=True)),
                ('site_tagline', models.CharField(default='Eat Right. Live Well.', max_length=200)),
            ],
            options={
                'verbose_name': 'Health Settings',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Meal Plan', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='health/videos/')),
                ('category', models.CharField(choices=[('general', 'General Health'), ('diabetes', 'Diabetes'), ('bp', 'Blood Pressure'), ('heart', 'Heart Health'), ('weight', 'Weight Loss'), ('recipes', 'Recipes'), ('herbs', 'Herbs & Spices'), ('yoga', 'Yoga & Exercise')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='videos', to='health.healthcondition')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/vegetables/')),
                ('description', models.TextField(blank=True)),
                ('nutrition', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('cooking_methods', models.TextField(blank=True)),
                ('best_time', models.CharField(blank=True, max_length=150)),
                ('serving_size', models.CharField(blank=True, max_length=150)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='vegetables', to='health.healthcondition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/recipes/')),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snacks'), ('drink', 'Drinks')], default='breakfast', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True, help_text='One per line')),
                ('steps', models.TextField(blank=True, help_text='One step per line')),
                ('nutrition', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('prep_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('cook_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='recipes', to='health.healthcondition')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snacks')], max_length=15)),
                ('custom', models.CharField(blank=True, max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='health.mealplan')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/herbs/')),
                ('description', models.TextField(blank=True)),
                ('traditional_uses', models.TextField(blank=True)),
                ('scientific_evidence', models.TextField(blank=True)),
                ('preparation', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='herbs', to='health.healthcondition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/fruits/')),
                ('description', models.TextField(blank=True)),
                ('nutrition', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('serving_size', models.CharField(blank=True, max_length=150)),
                ('best_time', models.CharField(blank=True, max_length=150)),
                ('diabetes_safe', models.BooleanField(default=True)),
                ('diabetes_note', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='fruits', to='health.healthcondition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snacks')], max_length=15)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='health.fooddiary')),
            ],
            options={
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/foods/')),
                ('description', models.TextField(blank=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('nutrition_facts', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('suitable_for', models.CharField(blank=True, max_length=300)),
                ('avoid_if', models.CharField(blank=True, max_length=300)),
                ('best_time', models.CharField(blank=True, max_length=200)),
                ('serving_size', models.CharField(blank=True, max_length=150)),
                ('cooking_methods', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='foods', to='health.healthcondition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('herb', 'Herb'), ('recipe', 'Recipe'), ('video', 'Video')], max_length=15)),
                ('item_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
    ]
