# Generated by Django 4.2.16 on 2026-07-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsettings',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
