# Generated by Django 4.2.16 on 2026-07-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthsettings_groq_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/journals/')),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('lifestyle', 'Lifestyle'), ('condition', 'Health Conditions'), ('recipe', 'Recipes'), ('herbs', 'Herbs & Natural Remedies'), ('fitness', 'Fitness & Exercise')], default='nutrition', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Short description shown on listing page')),
                ('content', models.TextField(help_text='Full article content')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube video')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fruit',
            name='condition_advice',
            field=models.TextField(blank=True, help_text='JSON: {"diabetes":{"can_eat":true,"note":"..."},...}'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='natural_treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fruit',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL'),
        ),
        migrations.AddField(
            model_name='herb',
            name='condition_advice',
            field=models.TextField(blank=True, help_text='JSON: {"diabetes":{"can_eat":true,"note":"..."},...}'),
        ),
        migrations.AddField(
            model_name='herb',
            name='natural_treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube cooking video URL'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='condition_advice',
            field=models.TextField(blank=True, help_text='JSON: {"diabetes":{"can_eat":true,"note":"..."},...}'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='natural_treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL'),
        ),
    ]
