# Generated by Django 4.2.16 on 2026-07-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_healthjournal_fruit_condition_advice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/guide/categories/')),
                ('icon', models.CharField(default='🥗', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health/guide/items/')),
                ('description', models.TextField(blank=True)),
                ('condition_advice', models.TextField(blank=True, help_text='JSON: {"diabetes":{"can_eat":"yes","note":"..."}, ...}')),
                ('recipe_content', models.TextField(blank=True, help_text='How to eat / cook content')),
                ('recipe_video_url', models.URLField(blank=True, help_text='YouTube cooking/how-to-eat video')),
                ('growing_content', models.TextField(blank=True, help_text='How to grow at home')),
                ('growing_video_url', models.URLField(blank=True, help_text='YouTube growing guide video')),
                ('journal_content', models.TextField(blank=True, help_text='Health article / journal content for this item')),
                ('nutrition', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('natural_treatment', models.TextField(blank=True, help_text='Natural remedy / medicinal use')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='health.foodcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItemGrowingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='health/guide/growing/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growing_images', to='health.fooditem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
