# Generated by Django 4.2.16 on 2026-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_foodcategory_fooditem_fooditemgrowingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='journal_video_url',
            field=models.URLField(blank=True, help_text='YouTube journal/article video'),
        ),
    ]
