# Generated by Django 4.2.16 on 2026-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_add_journal_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='growing_video',
            field=models.FileField(blank=True, null=True, upload_to='health/guide/videos/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='journal_video',
            field=models.FileField(blank=True, null=True, upload_to='health/guide/videos/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='recipe_video',
            field=models.FileField(blank=True, null=True, upload_to='health/guide/videos/'),
        ),
    ]
