# Generated by Django 4.2.16 on 2026-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_add_video_file_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='growing_youtube_channel',
            field=models.CharField(blank=True, help_text='YouTube channel name for growing video', max_length=200),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='journal_author',
            field=models.CharField(blank=True, help_text='Author / writer of journal article', max_length=200),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='journal_youtube_channel',
            field=models.CharField(blank=True, help_text='YouTube channel name for journal video', max_length=200),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='recipe_youtube_channel',
            field=models.CharField(blank=True, help_text='YouTube channel name for recipe video', max_length=200),
        ),
    ]
