# Generated by Django 4.2.16 on 2026-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_add_recipe_growing_video_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='advice_video',
            field=models.FileField(blank=True, null=True, upload_to='health/guide/videos/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='advice_video_url',
            field=models.URLField(blank=True, help_text='YouTube video for Health Advice tab'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='advice_youtube_channel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
