# Generated by Django 4.2.16 on 2026-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_add_advice_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='natural_treatment_video',
            field=models.FileField(blank=True, null=True, upload_to='health/guide/videos/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='natural_treatment_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='natural_treatment_youtube_channel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
